### ISSUE TITLE
Current gem release is broken

### ISSUE THREAD

**Issue by dg-ratiodata** [jasonlong/geo_pattern#42]
Hi there,

the currently released gem version is broken.

```
/home/user/.gem/ruby/2.1.5/gems/geo_pattern-1.3.1/lib/geo_pattern/pattern/diamond_pattern.rb:2:in `<module:GeoPattern>': uninitialized constant GeoPattern::BasePattern (NameError)
        from /home/user/.gem/ruby/2.1.5/gems/geo_pattern-1.3.1/lib/geo_pattern/pattern/diamond_pattern.rb:1:in `<top (required)>'
        from /home/user/.gem/ruby/2.1.5/gems/geo_pattern-1.3.1/lib/geo_pattern/pattern/pattern_helpers.rb:1:in `block in <top (required)>'
        from /home/user/.gem/ruby/2.1.5/gems/geo_pattern-1.3.1/lib/geo_pattern/pattern/pattern_helpers.rb:1:in `each'
        from /home/user/.gem/ruby/2.1.5/gems/geo_pattern-1.3.1/lib/geo_pattern/pattern/pattern_helpers.rb:1:in `<top (required)>'
        from /home/user/.gem/ruby/2.1.5/gems/geo_pattern-1.3.1/lib/geo_pattern.rb:3:in `<top (required)>'
        from /home/user/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `require'
        from /home/user/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /home/user/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `each'
        from /home/user/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `block in require'
        from /home/user/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `each'
        from /home/user/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `require'
        from /home/user/.gem/ruby/2.1.5/gems/bundler-1.7.9/lib/bundler.rb:134:in `require'
        from /home/user/data/projects/middleman-presentation-builder-new/config/application.rb:7:in `<top (required)>'
        from /home/user/.gem/ruby/2.1.5/gems/spring-1.2.0/lib/spring/application.rb:82:in `require'
        from /home/user/.gem/ruby/2.1.5/gems/spring-1.2.0/lib/spring/application.rb:82:in `preload'
        from /home/user/.gem/ruby/2.1.5/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
        from /home/user/.gem/ruby/2.1.5/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
        from /home/user/.gem/ruby/2.1.5/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
        from /home/user/.gem/ruby/2.1.5/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
        from /home/user/.gem/ruby/2.1.5/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /usr/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Would you mind to release a new gem version? Those PRs of mine you've already merged, fixed that. So just building a new gem and releasing it should be all which needs to be done.

For now I'm running on the `git`-version in my rails project

```
gem 'geo_pattern', git: 'https://github.com/jasonlong/geo_pattern.git'
```

**Comment by jasonlong** [comment]
Ok, I just pushed `1.3.2`. Let me know if that does the trick.

**Comment by dg-ratiodata** [comment]
Thanks a lot. Fixed. :-)
